DB: database.db
MONTH_NAMES:
- Сентябрь
- Октябрь
- Ноябрь
- Декабрь
- Январь
- Февраль
- Март
- Апрель
- Май
MONTH_NUMS:
- 9
- 10
- 11
- 12
- 1
- 2
- 3
- 4
- 5
PATH_SCREENSHOT: E:/Desktop/ТЕСТ/
PATH_SHEET: E:/Desktop/ТЕСТ/
WORK_DAYS:
- 2
- 4
YEARS:
- 2022
- 2023
font_size: 20
